development:
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5
  timeout: 5000

production:
  adapter: mysql
  database: reclamere
  username: reclamere
  password: rc1234
  socket: /var/run/mysqld/mysqld.sock
